#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
if ! command -v yarn &> /dev/null
then
  if [[ $- == *i* ]]
  then
    exec < /dev/tty && npm run cz --hook || true
    exit
  fi
fi

exec < /dev/tty && yarn cz --hook || true
